version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"        # Bu parola migrate ve webapp için kullanılacak
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: always

  migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    volumes:
      - .:/app
      - ./migrate.sh:/app/migrate.sh
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/app/migrate.sh"]

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8000
      ConnectionStrings__BaseDb: "Server=db;Database=OBiletCloneDb;User Id=sa;Password=Your_password123;TrustServerCertificate=true;"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: always

volumes:
  mssqldata:
